---
- name: "Сonfiguring the log server"
  hosts: log
  gather_facts: false
  roles:
    - log-role
  become: true

- name: "Сonfiguring the web server"
  hosts: web
  gather_facts: false
  roles:
    - nginx-role
  become: true

- name: "Сonfiguring the elk server"
  hosts: elk
  gather_facts: false
  roles:
    - elk-role
  become: true